version: 2
jobs:
  build:
    working_directory: ~/skeleton-api
    docker:
      - image: circleci/node:9.11
        environment:
          - NODE_APP_INSTANCE=ci
      - image: mysql:5.7.22
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: skeletontest
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint
          command: npm run lint:ci
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: npm run coverage:ci
      - store_test_results:
          path: ./reports/data
      - store_artifacts:
          path: ./reports/pretty
          destination: reports
