name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      NODE_APP_INSTANCE: ci

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: skeletontest
        ports:
          - 3306

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Deps
      run: npm install
    - name: Lint
      run: npm run lint:ci
    - name: Build
      run: npm run build
    - name: Test
      run: npm run coverage:ci
  
